### PR TITLE
fix up for package.json

### PR DESCRIPTION
**Pull request by jgadsden**
used for build-templates, as we discussed in the meeting last week, and also bundle-css

### CODE REVIEW

**Comment by jgadsden** [comment]
The minify-css and bundle-minify-css scripts do not seem to work for the core Threat Dragon owasp-threat-dragon-core repo. I have not removed them from package.json as we do not mind so much? Note tat these scripts do work for the Threat Dragon owasp-threat-dragon repo as expected.

**Comment by jgadsden** [comment]
Fix ups for minify-css and bundle-minify-css scripts

**Comment by mike-goodwin** [comment]
jon - this breaks the build-templates script on my machine (Windows 10). I wonder if there is a difference between Linux and Windows?

**Comment by mike-goodwin** [comment]
This change has been incorporated in commit 853bdd4607e45a74c3ca70c5b15b65e5ae0b52a5

**Pull request closed without merging**
