### PR TITLE
Create boundary name

### LINKED ISSUE #78: Add name to boundary
@andk123 writes
add a name to the boundary like this:

boundary-name

It can be useful to identify the origin of a said boundary when doing threat modelling

### PR DESCRIPTION
**Pull request by andk123**
#78 
Boundaries are now created with a label to be able to identify different boundaries similarly to a flow. It should not affect previous boundaries created (without a name) and they can still be saved without a name, or a name can be added if needed.

### CODE REVIEW

**Comment by andk123** [comment]
Will solve code refactoring.

**Review by jgadsden — COMMENTED** [review]
Many thanks @andk123 for this feature, looking good but I had a couple of questions:
- I could not see how to edit the boundary name from 'boundary 0' ?
- could we default with no name applied, so that it is added-functionality rather than changed-functionality?
The reasoning for the last point is that I had years of using cisco's Threat Modeller and always had to name the boundary. This was good sometimes, but mostly I did not need to name the boundary. So it is good to have it there, but maybe not as default.
Thanks again, Jon

**Comment by jgadsden** [comment]
Tested with the both old and new json model files, and also tested existing app with both old and new json model files, to ensure compatibility between releases and data model. All good!

Sorry @andk123 - somehow commented and also by mistake closed this request at the same time. Oops, finger trouble, have reopened it.

**Comment by andk123** [comment]
1. Okay I see. I was working mostly on the web app. The desktop app seems to behave a bit differently since the settings button does not appear (See picture taken in the web app). 
image
2. Now that I think of it, that is an excellent idea.

I will fix/implement both changes and create a new pull request @jgadsden. Thanks!

**Comment by andk123** [comment]
@jgadsden The two issues should be solved now. Let me know what you think.
Arnold

**Comment by andk123** [comment]
Everything is working now.

**Review by jgadsden — APPROVED** [review]
Hello @andk123 - tests out perfectly on my MacOS for both web app and also desktop app. There is the code climate complaint that is not significant, so all is good. Thanks again!

**Comment by jgadsden** [comment]
I can merge this pull request, but as an aside the code climate issue could be solved (if I understand correctly) by substituting : 
```
            if (newElement.attributes.type == "tm.Flow") {    
                newElement.attributes.source = {'x' : 30, 'y' : 20};
                newElement.attributes.target = {'x' : 110, 'y' : 100};
                newElement.attributes.labels[0].attrs.text.text = label;
                delete newElement.attributes.vertices;
            }
            else if (newElement.attributes.type == "tm.Boundary") {    
                newElement.attributes.source = {'x' : 30, 'y' : 20};
                newElement.attributes.target = {'x' : 110, 'y' : 100};
                if (label != ""){
                    newElement.attributes.labels[0].attrs.text.text = label;
                }
                delete newElement.attributes.vertices;
            }
```
with 
```
            if (newElement.attributes.type == "tm.Flow" || newElement.attributes.type == "tm.Boundary") {    
                newElement.attributes.source = {'x' : 30, 'y' : 20};
                newElement.attributes.target = {'x' : 110, 'y' : 100};
                if (label != ""){
                    newElement.attributes.labels[0].attrs.text.text = label;
                }
                delete newElement.attributes.vertices;
            }
```
as label is not empty for Flow. This brings the function lines below 25.
Shall I merge this PR as is?

**Comment by andk123** [comment]
> I can merge this pull request, but as an aside the code climate issue could be solved (if I understand correctly) by substituting :
> 
> ```
>             if (newElement.attributes.type == "tm.Flow") {    
>                 newElement.attributes.source = {'x' : 30, 'y' : 20};
>                 newElement.attributes.target = {'x' : 110, 'y' : 100};
>                 newElement.attributes.labels[0].attrs.text.text = label;
>                 delete newElement.attributes.vertices;
>             }
>             else if (newElement.attributes.type == "tm.Boundary") {    
>                 newElement.attributes.source = {'x' : 30, 'y' : 20};
>                 newElement.attributes.target = {'x' : 110, 'y' : 100};
>                 if (label != ""){
>                     newElement.attributes.labels[0].attrs.text.text = label;
>                 }
>                 delete newElement.attributes.vertices;
>             }
> ```
> 
> with
> 
> ```
>             if (newElement.attributes.type == "tm.Flow" || newElement.attributes.type == "tm.Boundary") {    
>                 newElement.attributes.source = {'x' : 30, 'y' : 20};
>                 newElement.attributes.target = {'x' : 110, 'y' : 100};
>                 if (label != ""){
>                     newElement.attributes.labels[0].attrs.text.text = label;
>                 }
>                 delete newElement.attributes.vertices;
>             }
> ```
> 
> as label is not empty for Flow. This brings the function lines below 25.
> Shall I merge this PR as is?

The 2nd method is good. Initially, I thought I would need to modify the boundary attributes, but I ended up keeping them as is. Code updated!

**Pull request merged**
